# Generated by Django 5.2 on 2025-04-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategory',
            name='tenant_id',
        ),
    ]
